version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/logseq-template-website
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 180
  ValidateService:
    - location: scripts/validation-service.sh
      timeout: 180