version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/logseq-template-website
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: killall node
  AfterInstall:
    - location: cd /home/ec2-user/logseq-template-website && npm ci
      timeout: 180
  ApplicationStart:
    - location: cd /home/ec2-user/logseq-template-website && node server.js
      timeout: 180
  ValidateService:
    - location: curl http://localhost:8080
      timeout: 180